server:
  port: 9100
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://git.lug.ustc.edu.cn/jinchen/springcloud.git
          username: jinchenemail@163.com
          password: gitlab18871150137
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
